<?php
/**
 * Created by PhpStorm
 * User: eapbachman
 * Date: 01/02/2020
 */

namespace twentyfourhoursmedia\poll\elements\db;

use craft\db\Query;
use craft\elements\db\EntryQuery;
use craft\models\Section;
use twentyfourhoursmedia\poll\Poll;
use twentyfourhoursmedia\poll\services\PollService;

class PollQuery extends EntryQuery
{

    public mixed $sectionId = null;

    /**
     * A cached section for polls
     * @var Section | null
     */
    private mixed $pollSections = null;

    /**
     * @var PollService
     */
    private mixed $pollService;

    public function __construct($elementType, array $config = [])
    {
        $this->pollService = Poll::$plugin->pollService;
        parent::__construct($elementType, $config);


    }

    /**
     * Returns the poll sections, cached
     *
     * @return array|Section|Section[]|null
     */
    private function getPollSections() {
        if (!$this->pollSections) {
            $this->pollSections = $this->pollService->getPollSections();
        }
        return $this->pollSections;
    }

    /**
     * Resets section ids so only poll sections are returned
     */
    private function resetSectionIds() {
        $this->sectionId = array_map(static function(Section $section) {
            return $section->id;
        }, $this->getPollSections());
    }


    /**
     * @param Section|string|string[]|null $value
     */
    public function section(mixed $value): EntryQuery {
        // reset section ids to limit only to poll sections
        $this->resetSectionIds();
        return $this;
    }

    public function prepare($builder): Query
    {
        // reset section ids
        $this->resetSectionIds();
        return parent::prepare($builder); // TODO: Change the autogenerated stub
    }


}