<?php
/**
 * Created by PhpStorm
 * User: eapbachman
 * Date: 01/02/2020
 */
namespace twentyfourhoursmedia\poll\elements\actions;
use Craft;
use craft\base\ElementAction;
use craft\elements\db\ElementQueryInterface;

class CreateReport extends ElementAction
{
    public static function isDestructive(): bool
    {
        return false;
    }



    public function getTriggerLabel(): string
    {
        return Craft::t('poll', 'Create report');
    }

    public function getTriggerHtml(): string
    {
        return '';
    }

    public function getConfirmationMessage(): string
    {
        return 'Create report?';
        return parent::getConfirmationMessage(); // TODO: Change the autogenerated stub
    }

    public function performAction(ElementQueryInterface $query): bool
    {
        return true;
        return parent::performAction($query); // TODO: Change the autogenerated stub
    }





}